### ISSUE TITLE
Organize your project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#110]
1.  project does not compile.
2.  project is not a Maven project.
3.  project has no test  source folder.
4. buildpath is wrong
5. package names are wrong
6. I find non java file (png????) in path

![image](https://cloud.githubusercontent.com/assets/12775400/22624679/ea1f3598-eb8b-11e6-920d-a3922d51e409.png)

**Comment by SlasherTech** [comment]
I checked with all the other team members and we all don't get such errors on our computers and the project is running and fulfilling the targets for this sprint (2) .
I will dig into this problem and do the required corrections.
As for the .png file - it is the project's logo. We thought it is OK to upload it here.
Should we just use a link to this picture instead of uploading it to GitHub ?

Thank you for your help and time.

@NetanelFelcher @viviansh @geniashand @ward-mattar @osherh

**Comment by yossigil** [comment]
Well, all I did was git clone and maven import. It did not work.
Note that problems in compilation are only related to item 1.
