### ISSUE TITLE
bug when inserting a query - does nothing

### ISSUE THREAD

**Issue by ravivos** [TechnionYP5777/Info-Evaluation#305]
bug when inserting a query - does nothing
<img width="468" alt="screenshot 2017-07-02 13 44 02" src="https://user-images.githubusercontent.com/7875588/27769275-30679d30-5f2f-11e7-9894-64a956ecbd3e.png">

**Comment by SlasherTech** [comment]
are you connected to a technion wifi ?

**Comment by SlasherTech** [comment]
NOT TECHPUBLIC

**Comment by ravivos** [comment]
I was connected to students_wifi when this happened

**Comment by SlasherTech** [comment]
I highly doubt that. We have a server log which monitors any input and function invocation in our system. Had your query been sent to our server, the least our log would show is your input. 
Since it didn't show, I would suggest you to make sure you are properly connected to a technion network. (again, not tech public) and try again.

**Comment by ravivos** [comment]
Nope, I am on students_wifi, you can come see for yourself in taub 7

**Comment by ravivos** [comment]
@MosheEliasof checked now with CS_WIFI and also doesn't work... nothing happens when pressing

**Comment by NetanelFelcher** [comment]
Just triedbit and it worked. Also, we checked our server's log and it didn't show that called that query, which means you are not connected to the Technion network (maybe your connection isn't stable).
