### ISSUE TITLE
Please give me edit permissions

### ISSUE THREAD

**Issue by yosefraisman** [TechnionYP5777/Info-Evaluation#309]

**Comment by yosefraisman** [comment]
attached is [my review](https://docs.google.com/document/d/1w47f1w8WxNejw04wKpJ-Nd20jh1Xo_r0eDg1nhaCjLM/edit?usp=sharing)

**Comment by SlasherTech** [comment]
Hi Yosef,
Thank you for your feedback.
I agree with your typo in the GUI - it was fixed.

Anyhow, regarding having issues with TechPublic WIFI , I must say that we explain in our user-guide that you need to be connected to a Technion network and we also gave students wifi as in example.
TechPublic is NOT considered a "closed" Technion network,since any user could connect to it.

The server we are using, provided by the faculty, must conform to the Technion's regulation. That is, it is accessible only from networks within the Technion. I hope this is clear now.
Thank you for your feeback.

**Comment by yossigil** [comment]
Is the title correct? @AdiOmari

**Comment by AdiOmari** [comment]
Should this be in a separate issue (the review)? or maybe rename the title.

**Comment by yosefraisman** [comment]
Not sure what you mean about the title. I have the necessary permissions now, anyway, moving my input to the wiki (hope that's fine).

**Comment by yossigil** [comment]
:+1:
