### ISSUE TITLE
Same Occupation - just 4 outputs

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/Info-Evaluation#319]
Really? only 4 people in the world fall under this query? hard to belive

**Comment by SlasherTech** [comment]
This is because our DB consists of 10,000 people from DBpedia. (which are randomly sampled)
We were provided with a small SQL server for the project, hence we could not use more people.
Anyhow - the point is to show the capabilities and not the quantity (which obviosly will enlarge as the DB we are working with will be bigger).
