### ISSUE TITLE
Revise Agile methodology

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#42]
I do not recall any group member in the lecture yesteday, but I may have missed one or two.

At any rate, I would like to suggest that the group meets to discuss:

1.  Personal responsibility
2. Team work
3. Steady rate of development
4. Agility

Pleas find someone to be assigned to this issue, add labels, milestones, as necessary:

@yh-github

**Comment by SlasherTech** [comment]
In our latests meeting ( 20.12.16) we discussed all the relevant subjects for agile methodology.
1. Each team member has a responsibility for a deliverable in the project. It is this member's responsibility to make sure he/she commits a code that is cleaned-up , spartanized and functional. That also means code with no errors nor warnings.

2.The projects is essentialy a team that works together in order to create a valuable product.
The team work is highly important for the success of the project.
Hence, we meet at least once a week in order to work together and we also communicate on a chat which includes all the team members.

3.By setting up deadlines and meeting regulary constant period of time we make sure the rate of productivity is steady.

4.We are working in a way that will yield the most value possible out of each piece of code we add to the project.
We reuse code in and use each other's code in our code.
For instance - when one is writing unit tests - instead of using writing stubs for the test, he/she can use classes that are already built and ready to work. (In case it fits the needs of the class he/she is developing).

@NetanelFelcher @ward-mattar @osherh @geniashand @viviansh

**Comment by yossigil** [comment]
:+1:
