### ISSUE TITLE
Your tests fail

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#43]
[testNames8239308132669046528.txt](https://github.com/TechnionYP5777/Info-Evaluation/files/664840/testNames8239308132669046528.txt)

**Comment by yossigil** [comment]
@yh-github

**Comment by SlasherTech** [comment]
@yossigil 
We ( @NetanelFelcher @geniashand & me) are in charge of the Analysis part in this sprint.
We checked all our tests before committing and pushing our files.
One prolem I could think of is the following:
CoreNLP (a library we are using in this project) requires a lot of memory to load up.
Hence, let 2GB of RAM for the tests to run.
We searched in Google and talked about it with Yoav and it seems like there is no other solution to it,as this is what using this library requiers.
I am pretty sure that allowing 2GB for the tests to run will solve the problem you have encountered.

Thank you for your time.

**Comment by osherh** [comment]
@yossigil, 
We(@viviansh @ward-mattar and I) are in charge of the GUI and DB part in this sprint.
As for this sprint we've decided to use a local mysql server.
I assume that the following tests: test.database.,MySQLConnectorTest & test.guiFrames.RefinementTableFunctionalityTest fail since MySQL server is not installed on your machine. You should install it first. The user should follow the wiki guide "How to setup MySQL Server on Local Host" before running the program.

**Comment by yossigil** [comment]
Mockito? Dependency injection?
