### ISSUE TITLE
Continous build

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Info-Evaluation#45]

**Comment by osherh** [comment]
what do you mean by continious build? Travis?

**Comment by yossigil** [comment]
What are my options? :-)

**Comment by osherh** [comment]
In order to eable the service we need admin access to the repository

**Comment by zahimizrahi** [comment]
@osherh 
In my project (ParkingManagement) , we had the same issue.
You can meet with Zvi so he would "open" your project to travis.
after that, you'll have to add file `travis.yml` to your project. 
There's a guide how to do that [here](https://docs.travis-ci.com/user/languages/java/) 
(note that you'll have to add some attributes to this file, depend on the environment your program should have in order to run). 
If you'll need some help, call me and I'll help you :)

**Comment by osherh** [comment]
@zvili , since we don't have admin access to this repository, could you please enable travis on our repository?

**Comment by yossigil** [comment]
@idabran ?

**Comment by osherh** [comment]
@idabran could you please activate the repository for us?

**Comment by osherh** [comment]
@yossigil Done.
